### ISSUE TITLE
The uploader is not working "name element not found"

### ISSUE THREAD

**Issue by sandcastle** [ivancrneto/hit2slack-emoji#1]
I'm having trouble trying to use the library - it looks like a element is no longer available:

```
ElementDoesNotExist: no elements could be found with name "name"
```

Full stack trace:

``` shell
Traceback (most recent call last):
  File "/usr/local/bin/catchemall", line 9, in <module>
    load_entry_point('hip2slack-emoji==0.2.0', 'console_scripts', 'catchemall')()
  File "/usr/local/lib/python2.7/site-packages/hip2slack_emoji/problem.py", line 136, in main
    importer.upload_all_the_things()
  File "/usr/local/lib/python2.7/site-packages/hip2slack_emoji/problem.py", line 86, in upload_all_the_things
    if self.deal_with_it(emoji):
  File "/usr/local/lib/python2.7/site-packages/hip2slack_emoji/problem.py", line 101, in deal_with_it
    fill_and_submit(emoji)
  File "/usr/local/lib/python2.7/site-packages/hip2slack_emoji/problem.py", line 95, in fill_and_submit
    browser.fill('name', emoji.name)
  File "/usr/local/lib/python2.7/site-packages/splinter/driver/webdriver/__init__.py", line 401, in fill
    field = self.find_by_name(name).first
  File "/usr/local/lib/python2.7/site-packages/splinter/element_list.py", line 53, in first
    return self[0]
  File "/usr/local/lib/python2.7/site-packages/splinter/element_list.py", line 44, in __getitem__
    self.find_by, self.query))
splinter.exceptions.ElementDoesNotExist: no elements could be found with name "name"
```

**Comment by ivancrneto** [comment]
Thank you for the feedback. It worked normally here. I have some questions that can help me:
1. Do you have permissions to upload emojis?
2. Did you try again? Sometimes there is a bad connection so it is not in the right page..
3. Was it able to upload any emoji or do this error happen in the first emoji?

**Comment by sandcastle** [comment]
hi @ivancrneto, please see my comments below:
1. yes, I'm the admin for the team
2. yes, I tried multiple times - it fails on the upload of the first item (all the things)
3. see above

The command I ran is below(email/password) removed - I tried both full URL and just the team name

``` shell
env SLACK_TEAM=deliver-this SLACK_EMAIL=XXX SLACK_PASS=XXX catchemall
```

**Comment by ivancrneto** [comment]
@sandcastle is it possible for us to do a screen share and fix this?

**Comment by pfcarrier** [comment]
@sandcastle @ivancrneto  :  I am curious did you find a work around ?  Running into the same exception [2 year later].
```
splinter.exceptions.ElementDoesNotExist: no elements could be found with name "name"
```

edited:  to show code as block code and the 2 year time bump.
