### ISSUE TITLE
HTMLParseError has been removed in Python 3.5

### ISSUE THREAD

**Issue by lots0logs** [ivancrneto/hit2slack-emoji#3]
```
Traceback (most recent call last):
  File "/usr/bin/catchemall", line 9, in <module>
    load_entry_point('hip2slack-emoji==0.2.0', 'console_scripts', 'catchemall')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 550, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2710, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/hip2slack_emoji/problem.py", line 7, in <module>
    from bs4 import BeautifulSoup
  File "/usr/lib/python3.5/site-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python3.5/site-packages/bs4/builder/__init__.py", line 308, in <module>
    from . import _htmlparser
  File "/usr/lib/python3.5/site-packages/bs4/builder/_htmlparser.py", line 7, in <module>
    from html.parser import (
ImportError: cannot import name 'HTMLParseError'

```

**Comment by lots0logs** [comment]
whoops I just noticed that this is an upstream issue. sorry!
